const MAIN_URL = process.env.NEXT_PUBLIC_PROXY_SERVICE_HOST;
const SEARCH_ROUTER = process.env.SEARCH_ROUTER;
const AUTH_SIGNUP_ROUTER = process.env.AUTH_SIGNUP_ROUTER;
const AUTH_LOGIN_ROUTER = process.env.AUTH_LOGIN_ROUTER;

//* HTTP의 ROUTER PATH
export const HTTP = Object.freeze({
  HOST: MAIN_URL,
  SEARCH: SEARCH_ROUTER,
  AUTH_SIGNUP: AUTH_SIGNUP_ROUTER,
  AUTH_LOGIN: AUTH_LOGIN_ROUTER,
});